#!/bin/bash
set -e
echo "Building..."
source $(dirname $0)/version

cd $(dirname $0)/..

mkdir -p bin
[ "$(uname)" != "Darwin" ] && LINKFLAGS="-linkmode external -extldflags -static -s"
CGO_ENABLED=0 go build -ldflags "-X main.Version=$VERSION -X main.GitCommit=$COMMIT -X main.BuildTime=`date -u '+%Y-%m-%d_%I:%M:%S%p'` $LINKFLAGS" -o bin/bashful
